### ISSUE TITLE
Nomic Models Not Using Query (or Document) Instructions

### ISSUE THREAD

**Issue by zanussbaum** [embeddings-benchmark/arena#21]
Hi @Muennighoff congrats on the launch! 

If I understand the code correctly, it seems like the [nomic](https://github.com/embeddings-benchmark/arena/blob/0f1b0e094ce6c9e8b182b50747156644d66a05b2/model_meta.yml#L170) models aren't using their instructions but should be using `search_query: {query}` and `search_document: {passage}` for all queries and documents: https://huggingface.co/nomic-ai/nomic-embed-text-v1.5#usage

In our internal tests, not using the prefixes harms model performance pretty significantly. 

Additionally for v1.5, there needs to be a layernorm placed after the output like here: https://huggingface.co/nomic-ai/nomic-embed-text-v1.5#sentence-transformers, however if it's easier to support I am happy to benchmark v1. 

Additionally, what's the best way to support document instructions? 

Let me know if you'd like me to contribute a PR!

**Comment by Muennighoff** [comment]
Thanks so much for raising this - I think you're right on the instruction issue. If it is not dataset-specific but just an instruction that should always be used then the best way is to modify it here: https://github.com/embeddings-benchmark/mteb/blob/main/mteb/models/nomic_models.py#L13 which is loaded in the arena via `mteb.get_model`. As soon as we have it fixed there, I will invalidate all Retrieval votes for nomic & recreate its indices - Super sorry about this. If you want to open a PR there, that'd be amazing so we can make sure we get it right.

I think the layernorm is happening here: https://github.com/embeddings-benchmark/mteb/blob/a1dc3ace5c2519dbb3e95401219aa2a518fe2bc8/mteb/models/nomic_models.py#L13 cc @KennethEnevoldsen but again feel free to modify this too if there's a better way to use the model.

**Comment by zanussbaum** [comment]
yes i'm happy to work on that PR! thanks for the speedy response. thanks for the handy link, that seems like it should cover most of it.

I think as far as retrieval, the instruction for document should always be the same, but that's not the same case for STS and Clustering. Is there a better way to add instructions for those other tasks? Is the `model_meta.yaml` the best place for that?

**Comment by Muennighoff** [comment]
>  but that's not the same case for STS and Clustering

Do you mean you want a different instruction for STS & Clustering? In that case you can add a `nomic_task_type` kwarg similar to e.g. here https://github.com/embeddings-benchmark/mteb/blob/2f2f65dc333687891f26efa82c68087127c18012/mteb/models/cohere_models.py#L46

& then pass it here https://github.com/embeddings-benchmark/arena/blob/0f1b0e094ce6c9e8b182b50747156644d66a05b2/models.py#L287

**Comment by zanussbaum** [comment]
@Muennighoff opened PR in mteb here: https://github.com/embeddings-benchmark/mteb/pull/1125 and some small changes to Arena I faced when debugging: https://github.com/embeddings-benchmark/arena/pull/26

It also seems like the dataset here is [private](https://github.com/embeddings-benchmark/arena/blob/main/models.py#L171), do we want to open it up?

**Comment by Muennighoff** [comment]
> It also seems like the dataset here is [private](https://github.com/embeddings-benchmark/arena/blob/main/models.py#L171), do we want to open it up?

Ofc sorry everything should be open-source -- It is open now: https://github.com/embeddings-benchmark/arena/blob/70cc614361c5dfcf5a4ca763499c0f4420a83b46/models.py#L174

**Comment by Muennighoff** [comment]
I'm recreating the indices right now & once done I will remove all old nomic votes via https://github.com/embeddings-benchmark/arena/blob/main/scripts/remove_votes.py

**Comment by zanussbaum** [comment]
thank you for the fast turnaround!

**Comment by Muennighoff** [comment]
Put Nomic back in the arena with new indices & removed its past votes. Below an example of Nomic beating SFR on Retrieval -- it looks good to me now, wdyt?
<img width="1248" alt="Screenshot 2024-07-31 at 7 29 22 AM" src="https://github.com/user-attachments/assets/e08f6320-9848-492c-b056-2503d0c4a313">

Would be great if you could do a bit of voting in the anonymous Battle Arenas so we can put nomic back into the leaderboard again soon! 🙌

**Comment by zanussbaum** [comment]
I missed this message but yes agreed it looks good to me!
